framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
#    secrets:
#        enabled: true
#        vault_directory: '/var/www/html/config/secrets/%env(default:kernel.environment:APP_RUNTIME_ENV)%'
#        local_dotenv_file: /var/www/html/.env.dev.local
#        decryption_env_var: 'base64:default::SYMFONY_DECRYPTION_SECRET'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
