parameters:
    app.api.url: 'https://free.currconv.com/api/v7/convert?compact=ultra&apiKey=%env(resolve:APP_API_KEY)%'
    app.api.homepage: 'https://fixer.io/'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Service\CurrencyConverter:
        arguments:
            $api: '%app.api.url%'

    App\Command\AwesomeCommand:
        tags:
            - { name: console.command, command: 'my:awesome:command'}