parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'



    App\Listener\OrderCanceledListener:
        tags:
            - { name: kernel.event_listener, event: !php/const App\Event\OrderCanceledEvent::NAME}

    App\Listener\ExceptionListener:
        tags:
#          - { name: kernel.event_listener, event: kernel.exception }
          - { name: kernel.event_listener, event: kernel.exception, method: logException }