imports:
    - { resource: 'sweet.xml',  ignore_errors: true }
    - { resource: 'sweet.xml',  ignore_errors: not_found }
parameters:
    app.secret: '%env(DATABASE_PASSWORD)%'
    app.database_url: '%env(resolve:DATABASE_URL)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'